### ISSUE TITLE
Fatal Error When Installing SyncGitlab2MSProject With Pipx or Pip

### ISSUE THREAD

**Issue by AvramSNeal** [CarliJoy/SyncGitlab2MSProject#24]
# Summary
When attempting to install/deploy the SyncGitlab2MSProject package with pipx (or pip) the following error occurs:

**Could not find a version that satisfies the requirement SyncGitlab2MSProject (from versions: )
No matching distribution found for SyncGitlab2MSProject**

# More Details
You can recreate the error by following the steps in the Quickstart section or running the pip install found on PyPi.
- https://github.com/CarliJoy/SyncGitlab2MSProject#quickstart
- https://pypi.org/project/SyncGitlab2MSProject/

### Assignees
@CarliJoy @AvramSNeal 

The outcome should look like this:
![image](https://github.com/CarliJoy/SyncGitlab2MSProject/assets/56975611/2ccff266-eab6-44f6-8e13-82530767f3b8)

# Conditions of Satisfaction
- The user should be able to run pipx or pip to install SyncGitlab2MSProject without any errors.
- SyncGitlab2MSProject should be able to run after it is installed with `sync_gitlab2msproject`
  - Usage: https://github.com/CarliJoy/SyncGitlab2MSProject#usage

**Comment by CarliJoy** [comment]
What kind of operating system are you using?
As stated within the Readme

> This project runs only in an Windows Environment with Microsoft Project installed.

**Comment by AvramSNeal** [comment]
I am using Windows 10. I was running pipx and pip in WSL, but if necessary I can use another method. The problem is pipx and pip both have issues finding SyncGitlab2MSProject.
![image](https://github.com/CarliJoy/SyncGitlab2MSProject/assets/56975611/1432e0ed-175e-4dee-b7cf-6c49073ea795)

**Comment by CarliJoy** [comment]
You can't run it in WSL -> that actually means that you run it within Linux, even so it is only emulated.
You need a native Windows Python for it to work,.

**Comment by AvramSNeal** [comment]
Okay, I installed using native Windows Python. Now after running the command in step 3, I get an error that the term is not recognized. Is there another missing step?

> 3. Push the gitlab Issue to your MS Project file: `sync_gitlab2msproject --gitlab-url https://gitlab.company.com --gitlab-token <your_token> group <your_group_id> ms_project_file.mpp`

![image](https://github.com/CarliJoy/SyncGitlab2MSProject/assets/56975611/d887c52b-d897-45bb-a66c-06274f5b84c3)

**Comment by CarliJoy** [comment]
If you used pipx you might need to run `pipx ensurepath`.
Please refer to the [pipx](https://pypa.github.io/pipx/#on-windows-install-via-pip-requires-pip-190-or-later) documentation for details.
Also I never used the powershell. So I have no Idea how it works. Try the simple old command line (`cmd`).

**Comment by AvramSNeal** [comment]
After much troubleshooting, I've successfully installed SyncGitlab2MSProject. There seemed to be an issue installing/running SyncGitlab2MSProject if the Python version was too far newer than 3.8. I can't say for sure whether different 3.8.x versions (like 3.8.4 or 3.8.16) would work, but 3.7.2 and 3.11.4 did NOT work.

Also, I don't have Microsoft Project on this machine so I received the `ERROR: Could not open 'ms_project_file.mpp' - seems not to be a valid file.` message, as expected. I will be installing it on a machine with Microsoft Project installed to verify functionality.
![image](https://github.com/CarliJoy/SyncGitlab2MSProject/assets/56975611/bc3a1112-8d92-447d-a709-4e6a92ec708d)


I'm including the steps I took after starting over to get the application installed and running.

### Steps to Setup and Run (Windows 10 ONLY)
* Verify you have no versions of Python already installed UNLESS it is 3.8.10.
  * Download and Install [Python 3.8.10 here](https://www.python.org/ftp/python/3.8.10/python-3.8.10-amd64.exe). You will want to make sure it gets added to the system path during setup, or you can do it from `System Properties > Advanced > Environment Variables`, then under **System variables** select **Path** and **Edit** to add the Python directories.
  * Run `python -V` in Command Prompt to verify. You should see **Python 3.8.10**. (Verify that you ONLY have Python 3.8.10 and no other version installed.)
* Now you may install [pipx](https://github.com/pypa/pipx#on-windows-install-via-pip-requires-pip-190-or-later)
  * Run `python -m pip install --user pipx`
  * Run `python -m pipx ensurepath`
* Install SyncGitlab2MSProject
  * Run `pipx install SyncGitlab2MSProject`
* Finally, run SyncGitlab2MSProject with your GitLab access token and the group ID from the desired project.
  * Run `sync_gitlab2msproject --gitlab-url https://gitlab.company.com --gitlab-token <your_token> group <your_group_id> ms_project_file.mpp`

**Comment by AvramSNeal** [comment]
I've installed Microsoft Project on this PC, and ran `sync_gitlab2msproject` according to the instructions provided in the GitHub ReadMe documentation. Unfortunately, I've still encountered errors. Please advise if there is anything I can do to make this run properly.

![SyncGitlab2MSProject-Error-groupsync](https://github.com/CarliJoy/SyncGitlab2MSProject/assets/56975611/234108a7-3051-46f6-bd64-a793cec02a0d)

**Comment by CarliJoy** [comment]
Sorry but without access to MS Project I am unable to test this anymore.

Also I don't have time for in dept debugging. It's open source. Feel free to debug yourself.

**Comment by CarliJoy** [comment]
Issue seems to be, that the issue id referenced in the project file couldn't be found.

**Comment by AvramSNeal** [comment]
No worries. I appreciate all of your help. I just wanted to try using this before writing my own script.
