### ISSUE TITLE
Issues do not have group_id attribute

### ISSUE THREAD

**Issue by BeeFishy** [CarliJoy/SyncGitlab2MSProject#7]
Running GitLab Enterprise Edition 13.3.6-ee.  Running with the "project" command line argument, I get an exception at https://github.com/CarliJoy/SyncGitlab2MSProject/blob/master/src/syncgitlab2msproject/sync.py#L43 on issue.group_id.  

Looking at the JSON, issues returned from my GitLab instance do not include a group_id attribute (there is a group_id attribute on milestones if the issue is assigned to a milestone).

Issue attributes in the returned JSON are:

'id', 'iid', 'project_id', 'title', 'description', 'state', 'created_at', 'updated_at', 'closed_at', 'closed_by', 'labels', 'milestone', 'assignees', 'author', 'assignee', 'user_notes_count', 'merge_requests_count', 'upvotes', 'downvotes', 'due_date', 'confidential', 'discussion_locked', 'web_url', 'time_stats', 'task_completion_status', 'weight', 'blocking_issues_count', 'has_tasks', '_links', 'references', 'moved_to_id'

Would it be possible to pass group_id in as a command line argument or substitute another field in creating that reference?

**Comment by CarliJoy** [comment]
Hi BeeFishy,

indeed I have not tested it with the project command line argument that much.
Thank you for your feedback. Good to know somebody is using it.
I will look into it, maybe I can figure out a way to receive the group_id by reading the project before hand.
Might takes a moment.

**Comment by CarliJoy** [comment]
@BeeFishy could you check if the bug is fixed with this version https://github.com/CarliJoy/SyncGitlab2MSProject/tree/fix_missing_group ?

Thank you :-)

**Comment by BeeFishy** [comment]
It did not like the reference to project.namespace.

```
Traceback (most recent call last):
  File "C:\src\SyncGitlab2MSProject\venv\lib\site-packages\gitlab\base.py", line 59, in __getattr__
    return self.__dict__["_updated_attrs"][name]
KeyError: 'namespace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\src\SyncGitlab2MSProject\venv\lib\site-packages\gitlab\base.py", line 62, in __getattr__
    value = self.__dict__["_attrs"][name]
KeyError: 'namespace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\src\SyncGitlab2MSProject\venv\lib\site-packages\gitlab\base.py", line 82, in __getattr__
    return self.__dict__["_parent_attrs"][name]
KeyError: 'namespace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\src\SyncGitlab2MSProject\src\syncgitlab2msproject\cli.py", line 233, in <module>
    run()
  File "C:\src\SyncGitlab2MSProject\src\syncgitlab2msproject\cli.py", line 229, in run
    main(sys.argv[1:])
  File "C:\src\SyncGitlab2MSProject\src\syncgitlab2msproject\cli.py", line 214, in main
    issues = get_issues_func(gitlab, args.gitlab_resource_id)
  File "c:\src\syncgitlab2msproject\src\syncgitlab2msproject\gitlab_issues.py", line 233, in get_project_issues
    return [
  File "c:\src\syncgitlab2msproject\src\syncgitlab2msproject\gitlab_issues.py", line 234, in <listcomp>
    Issue(issue, fixed_group_id=get_group_id_from_gitlab_project(project))
  File "c:\src\syncgitlab2msproject\src\syncgitlab2msproject\gitlab_issues.py", line 212, in get_group_id_from_gitlab_project
    namespace: Dict[str, Union[int, str]] = project.namespace
  File "C:\src\SyncGitlab2MSProject\venv\lib\site-packages\gitlab\base.py", line 84, in __getattr__
    raise AttributeError(name)
AttributeError: namespace
```

**Comment by CarliJoy** [comment]
That is strange.
If I look into the [13.6. documentation](https://docs.gitlab.com/13.6/ee/api/projects.html) namespace is defined.

Are you using token auth or is a public project you accessing without key?

I see in the documentation gitlab delivers different results for each case
> When simple=true or the **user is unauthenticated** this returns something like:

If you use no token, could you try to use one?
I still will think of a solution.

BR

Carli*

**Comment by BeeFishy** [comment]
This access is using token auth on a non-public server.

When I follow the link in the issue and access the project via the REST API (e.g. https://<gitlab host>/api/v4/projects/1234) it does have a namespace object.  Perhaps you're missing a request in the chain?

**Comment by CarliJoy** [comment]
That's strange.
I am using python-gitlab to access gitlab. So it should take care of getting the correct results.

But it could be due to the fact, that I was using the `lazy` parameter for receiving projects.
**Please try again.**

I am now catching the attribute error and only warn, as the attribute is not required to sync correctly.
So following the KISS principle I don't want to put more "hacks" into it.

Still I would be interested why the attributes can't be accessed....

**Comment by BeeFishy** [comment]
Yeah, it's working now.  Didn't see any additional output if you output something in the case of catching the error.  On to my next issue.  :-)
