### ISSUE TITLE
Handle Issues without Time Estimated or Spent

### ISSUE THREAD

**Issue by BeeFishy** [CarliJoy/SyncGitlab2MSProject#9]
New issues may not have a time estimate or time spent set.  In my case, I'm doing Agile and using the weight field to represent story points and not using time estimates at all.

I get exceptions on https://github.com/CarliJoy/SyncGitlab2MSProject/blob/master/src/syncgitlab2msproject/sync.py#L136 and https://github.com/CarliJoy/SyncGitlab2MSProject/blob/master/src/syncgitlab2msproject/sync.py#L141 when it tries to reference the time_estimated and time_spent_total attributes.

**Comment by CarliJoy** [comment]
Please provide the full stack and with all exceptions.

Please provide also the output of `pip freeze`

Somehow either your gitlab installation behaves really different or something is really strange here.

As this is the second similar issue I would like to dig a bit deeper instead of doing a superficial fix like before.

**Comment by CarliJoy** [comment]
@BeeFishy please provide the requested information so I can help you 😃

**Comment by BeeFishy** [comment]
(venv) D:\src\SyncGitlab2MSProject>python src\syncgitlab2msproject\cli.py --gitlab-url $URL --gitlab-token $TOKEN project 3844 TestProject.mpp
Traceback (most recent call last):
  File "D:\src\SyncGitlab2MSProject\src\syncgitlab2msproject\cli.py", line 233, in <module>
    run()
  File "D:\src\SyncGitlab2MSProject\src\syncgitlab2msproject\cli.py", line 229, in run
    main(sys.argv[1:])
  File "D:\src\SyncGitlab2MSProject\src\syncgitlab2msproject\cli.py", line 221, in main
    sync_gitlab_issues_to_ms_project(
  File "d:\src\syncgitlab2msproject\src\syncgitlab2msproject\sync.py", line 313, in sync_gitlab_issues_to_ms_project
    synced += update_task_with_issue_data(
  File "d:\src\syncgitlab2msproject\src\syncgitlab2msproject\sync.py", line 136, in update_task_with_issue_data
    task.work = int(issue.time_estimated)
  File "d:\src\syncgitlab2msproject\src\syncgitlab2msproject\gitlab_issues.py", line 189, in time_estimated
    return self.obj.time_stats["time_estimate"] / 60
TypeError: 'method' object is not subscriptable


pip freeze:
(venv) D:\src\SyncGitlab2MSProject>pip freeze
certifi==2020.12.5
chardet==4.0.0
idna==2.10
python-dateutil==2.8.1
python-gitlab==2.6.0
pywin32==300
requests==2.25.1
requests-toolbelt==0.9.1
six==1.15.0
-e git+https://github.com/CarliJoy/SyncGitlab2MSProject.git@207537f428e3d95aa794f0af236a50043b520576#egg=SyncGitlab2MSProject
urllib3==1.26.3

**Comment by BeeFishy** [comment]
I made these changes to allow it to move past the issue:

```
diff --git a/src/syncgitlab2msproject/sync.py b/src/syncgitlab2msproject/sync.py
index c452838..2b9e344 100644
--- a/src/syncgitlab2msproject/sync.py
+++ b/src/syncgitlab2msproject/sync.py
@@ -132,13 +132,13 @@ def update_task_with_issue_data(
             task.notes = issue.description
             if issue.due_date is not None:
                 task.deadline = issue.due_date
-            if not task.has_children:
+            if not task.has_children and hasattr(task, "time_estimated"):
                 task.work = int(issue.time_estimated)
             # Update duration in case it seems to be default
             if task.duration == DEFAULT_DURATION and task.estimated:
                 if task.work > 0:
                     task.duration = task.work
-            task.actual_work = issue.time_spent_total
+#            task.actual_work = issue.time_spent_total
             if issue.has_tasks or task.percent_complete == 0:
                 task.percent_complete = issue.percentage_tasks_done
             task.hyperlink_name = "Open in Gitlab"

```

**Comment by CarliJoy** [comment]
Could you please try the branch https://github.com/CarliJoy/SyncGitlab2MSProject/tree/fix_time_stats_calls and tell me if it throws warnings?

**Comment by BeeFishy** [comment]
Nope, it works.

**Comment by CarliJoy** [comment]
Thanks for testing.
